"""initialize database

Revision ID: 3435010a45b9
Revises: 
Create Date: 2019-11-21 14:06:27.031133

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utc
import app.sql.columns

# revision identifiers, used by Alembic.
revision = '3435010a45b9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collection',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=64, _expect_unicode=True), nullable=False),
    sa.Column('username', sa.String(length=16, _expect_unicode=True), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('archived', sa.Boolean(), nullable=True),
    sa.Column('created_at', sqlalchemy_utc.sqltypes.UtcDateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sqlalchemy_utc.sqltypes.UtcDateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('feature_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('modelzoo_name', sa.String(length=64, _expect_unicode=True), nullable=False),
    sa.Column('index_type', sa.String(length=16, _expect_unicode=True), nullable=False),
    sa.Column('username', sa.String(length=16, _expect_unicode=True), nullable=True),
    sa.Column('created_at', sqlalchemy_utc.sqltypes.UtcDateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sqlalchemy_utc.sqltypes.UtcDateTime(timezone=True), nullable=True),
    sa.Column('process_id', sa.Integer(), nullable=True),
    sa.Column('processed_at', sqlalchemy_utc.sqltypes.UtcDateTime(timezone=True), nullable=True),
    sa.Column('index_id', sa.Integer(), nullable=True),
    sa.Column('indexed_at', sqlalchemy_utc.sqltypes.UtcDateTime(timezone=True), nullable=True),
    sa.Column('index_settings', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('modelzoo_name')
    )
    op.create_table('media',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mediaType', app.sql.columns.media_type_column.MediaTypeColumn(), nullable=False),
    sa.Column('sha256', app.sql.columns.hash_column.HashColumn(length=32), nullable=False),
    sa.Column('ext', sa.String(length=4, _expect_unicode=True), nullable=False),
    sa.Column('frame', sa.Integer(), nullable=True),
    sa.Column('created_at', sqlalchemy_utc.sqltypes.UtcDateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('uploads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sha256', app.sql.columns.hash_column.HashColumn(length=32), nullable=False),
    sa.Column('ext', sa.String(length=4, _expect_unicode=True), nullable=False),
    sa.Column('username', sa.String(length=16, _expect_unicode=True), nullable=False),
    sa.Column('created_at', sqlalchemy_utc.sqltypes.UtcDateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('collection_media',
    sa.Column('collection_id', sa.Integer(), nullable=False),
    sa.Column('media_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=16, _expect_unicode=True), nullable=False),
    sa.Column('created_at', sqlalchemy_utc.sqltypes.UtcDateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['collection_id'], ['collection.id'], ),
    sa.ForeignKeyConstraint(['media_id'], ['media.id'], ),
    sa.PrimaryKeyConstraint('collection_id', 'media_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('collection_media')
    op.drop_table('uploads')
    op.drop_table('media')
    op.drop_table('feature_type')
    op.drop_table('collection')
    # ### end Alembic commands ###
